name: sweatmark
description: A high-fidelity fitness application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  google_fonts: ^6.0.0
  provider: ^6.0.0
  phosphor_flutter: ^2.0.0
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.0
  table_calendar: ^3.0.9
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
